BEGIN;

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    login VARCHAR(60) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    nivel VARCHAR(10) NOT NULL DEFAULT 'USER',
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_login UNIQUE (login),
    CONSTRAINT ck_usuario_nivel CHECK (nivel IN ('MASTER', 'USER'))
);

CREATE TABLE cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(14),
    telefone VARCHAR(20),
    email VARCHAR(150),
    endereco VARCHAR(180),
    numero VARCHAR(20),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf CHAR(2),
    cep VARCHAR(10),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uk_cliente_cpf UNIQUE (cpf),
    CONSTRAINT uk_cliente_email UNIQUE (email)
);

CREATE TABLE fornecedor (
    id_fornecedor BIGINT GENERATED BY DEFAULT AS IDENTITY,
    razao_social VARCHAR(180) NOT NULL,
    nome_fantasia VARCHAR(150),
    cnpj VARCHAR(18) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(150),
    endereco VARCHAR(180),
    numero VARCHAR(20),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf CHAR(2),
    cep VARCHAR(10),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_fornecedor PRIMARY KEY (id_fornecedor),
    CONSTRAINT uk_fornecedor_cnpj UNIQUE (cnpj),
    CONSTRAINT uk_fornecedor_email UNIQUE (email)
);

CREATE TABLE produto (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY,
    descricao VARCHAR(180) NOT NULL,
    unidade VARCHAR(10) NOT NULL DEFAULT 'UN',
    preco_custo NUMERIC(12,2) NOT NULL DEFAULT 0,
    preco_venda NUMERIC(12,2) NOT NULL DEFAULT 0,
    estoque NUMERIC(12,3) NOT NULL DEFAULT 0,
    estoque_minimo NUMERIC(12,3) NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_produto PRIMARY KEY (id_produto),
    CONSTRAINT ck_produto_preco_custo CHECK (preco_custo >= 0),
    CONSTRAINT ck_produto_preco_venda CHECK (preco_venda >= 0),
    CONSTRAINT ck_produto_estoque CHECK (estoque >= 0),
    CONSTRAINT ck_produto_estoque_minimo CHECK (estoque_minimo >= 0)
);

CREATE TABLE venda (
    id_venda BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    data_venda TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    forma_pagamento VARCHAR(20) NOT NULL DEFAULT 'AVISTA',
    quantidade_parcelas INTEGER NOT NULL DEFAULT 1,
    valor_total NUMERIC(14,2) NOT NULL DEFAULT 0,
    status VARCHAR(15) NOT NULL DEFAULT 'ABERTA',
    CONSTRAINT pk_venda PRIMARY KEY (id_venda),
    CONSTRAINT fk_venda_cliente FOREIGN KEY (id_cliente)
        REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_venda_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_venda_forma_pagamento
        CHECK (forma_pagamento IN ('AVISTA', 'PARCELADO')),
    CONSTRAINT ck_venda_quantidade_parcelas CHECK (quantidade_parcelas > 0),
    CONSTRAINT ck_venda_valor_total CHECK (valor_total >= 0),
    CONSTRAINT ck_venda_status
        CHECK (status IN ('ABERTA', 'FINALIZADA', 'CANCELADA'))
);

CREATE TABLE compra (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_fornecedor BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    data_compra TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    forma_pagamento VARCHAR(20) NOT NULL DEFAULT 'AVISTA',
    quantidade_parcelas INTEGER NOT NULL DEFAULT 1,
    valor_total NUMERIC(14,2) NOT NULL DEFAULT 0,
    status VARCHAR(15) NOT NULL DEFAULT 'ABERTA',
    CONSTRAINT pk_compra PRIMARY KEY (id_compra),
    CONSTRAINT fk_compra_fornecedor FOREIGN KEY (id_fornecedor)
        REFERENCES fornecedor (id_fornecedor)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_compra_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_compra_forma_pagamento
        CHECK (forma_pagamento IN ('AVISTA', 'PARCELADO')),
    CONSTRAINT ck_compra_quantidade_parcelas CHECK (quantidade_parcelas > 0),
    CONSTRAINT ck_compra_valor_total CHECK (valor_total >= 0),
    CONSTRAINT ck_compra_status
        CHECK (status IN ('ABERTA', 'FINALIZADA', 'CANCELADA'))
);

CREATE TABLE produtos_venda (
    id_produto_venda BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_venda BIGINT NOT NULL,
    id_produto BIGINT NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    valor_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(14,2) NOT NULL,
    CONSTRAINT pk_produtos_venda PRIMARY KEY (id_produto_venda),
    CONSTRAINT fk_produtos_venda_venda FOREIGN KEY (id_venda)
        REFERENCES venda (id_venda)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_produtos_venda_produto FOREIGN KEY (id_produto)
        REFERENCES produto (id_produto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT uk_produtos_venda UNIQUE (id_venda, id_produto),
    CONSTRAINT ck_produtos_venda_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_produtos_venda_valor_unitario CHECK (valor_unitario >= 0),
    CONSTRAINT ck_produtos_venda_subtotal CHECK (subtotal >= 0)
);

CREATE TABLE produtos_compra (
    id_produto_compra BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_compra BIGINT NOT NULL,
    id_produto BIGINT NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    valor_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(14,2) NOT NULL,
    CONSTRAINT pk_produtos_compra PRIMARY KEY (id_produto_compra),
    CONSTRAINT fk_produtos_compra_compra FOREIGN KEY (id_compra)
        REFERENCES compra (id_compra)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_produtos_compra_produto FOREIGN KEY (id_produto)
        REFERENCES produto (id_produto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT uk_produtos_compra UNIQUE (id_compra, id_produto),
    CONSTRAINT ck_produtos_compra_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_produtos_compra_valor_unitario CHECK (valor_unitario >= 0),
    CONSTRAINT ck_produtos_compra_subtotal CHECK (subtotal >= 0)
);

CREATE TABLE contas_pagar (
    id_conta_pagar BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_compra BIGINT NOT NULL,
    numero_parcela INTEGER NOT NULL,
    data_emissao DATE NOT NULL DEFAULT CURRENT_DATE,
    data_vencimento DATE NOT NULL,
    valor_parcela NUMERIC(14,2) NOT NULL,
    valor_pago NUMERIC(14,2) NOT NULL DEFAULT 0,
    data_pagamento DATE,
    status VARCHAR(15) NOT NULL DEFAULT 'ABERTA',
    observacao VARCHAR(255),
    CONSTRAINT pk_contas_pagar PRIMARY KEY (id_conta_pagar),
    CONSTRAINT fk_contas_pagar_compra FOREIGN KEY (id_compra)
        REFERENCES compra (id_compra)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT uk_contas_pagar_parcela UNIQUE (id_compra, numero_parcela),
    CONSTRAINT ck_contas_pagar_numero_parcela CHECK (numero_parcela > 0),
    CONSTRAINT ck_contas_pagar_valor_parcela CHECK (valor_parcela > 0),
    CONSTRAINT ck_contas_pagar_valor_pago CHECK (valor_pago >= 0),
    CONSTRAINT ck_contas_pagar_status
        CHECK (status IN ('ABERTA', 'PAGA', 'CANCELADA'))
);

CREATE TABLE contas_receber (
    id_conta_receber BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_venda BIGINT NOT NULL,
    numero_parcela INTEGER NOT NULL,
    data_emissao DATE NOT NULL DEFAULT CURRENT_DATE,
    data_vencimento DATE NOT NULL,
    valor_parcela NUMERIC(14,2) NOT NULL,
    valor_recebido NUMERIC(14,2) NOT NULL DEFAULT 0,
    data_recebimento DATE,
    status VARCHAR(15) NOT NULL DEFAULT 'ABERTA',
    observacao VARCHAR(255),
    CONSTRAINT pk_contas_receber PRIMARY KEY (id_conta_receber),
    CONSTRAINT fk_contas_receber_venda FOREIGN KEY (id_venda)
        REFERENCES venda (id_venda)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT uk_contas_receber_parcela UNIQUE (id_venda, numero_parcela),
    CONSTRAINT ck_contas_receber_numero_parcela CHECK (numero_parcela > 0),
    CONSTRAINT ck_contas_receber_valor_parcela CHECK (valor_parcela > 0),
    CONSTRAINT ck_contas_receber_valor_recebido CHECK (valor_recebido >= 0),
    CONSTRAINT ck_contas_receber_status
        CHECK (status IN ('ABERTA', 'RECEBIDA', 'CANCELADA'))
);

INSERT INTO usuario (
    nome,
    login,
    senha,
    nivel,
    ativo
)
VALUES (
    'Administrador',
    'master',
    '1234',
    'MASTER',
    TRUE
)


INSERT INTO usuario (
    nome,
    login,
    senha,
    nivel,
    ativo
)
VALUES (
    'Usuario Teste',
    'user',
    '1234',
    'USER',
    TRUE
)


COMMIT;
